version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /rmatsTurboOneGroup.wdl
    testParameterFiles:
      - /test_bam_default_one_group.json
    authors:
      - orcid: 0000-0002-3008-3375
